version: '2'
services:
  jupyter:
    image: mv/jupyter/language:latest
    build: .
    user: jovyan
    volumes:
      - ./notebooks/:/home/jovyan/work/
    ports:
      - "8892:8888"
    links:
      - redis
    depends_on:
      - spacyd

  spacyd:
    image: mv/spacyd:latest
    build: ./spacyd
    links:
      - redis

  redis:
    image: redis:3.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/
